# https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions
# https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle
name: Run test and publish living doc

on:
  pull_request:
    branches:
      - main

jobs:
  gradle-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Get up Selenium Standalone-Chrome within Docker
      run: docker run -d -p 4444:4444 --shm-size="2g" selenium/standalone-chrome:4.7.2-20221219

    - name: Execute Test
      run: ./gradlew test

    - name: Serenity living doc
      uses: actions/upload-artifact@v3
      with:
        name: serenity-report
        path: /home/runner/work/Screenplay-Serenity-BDD-automatization/Screenplay-Serenity-BDD-automatization/target/site/serenity/
        if-no-files-found: error

  deploy:
    needs: gradle-test
    runs-on: ubuntu-latest
    environment:
      name: 'Report'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: serenity-report
        path: .

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      id: deploy-to-webapp
      with:
        app-name: 'serenity-living-doc'
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}

